# Generated by Django 4.2.11 on 2024-04-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_title', models.CharField(max_length=252)),
                ('education_description', models.CharField(max_length=252)),
                ('education_published', models.BooleanField()),
                ('education_year', models.CharField(max_length=50)),
                ('education_created', models.DateTimeField(auto_now=True)),
                ('education_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=50)),
                ('language_level', models.CharField(max_length=50)),
                ('language_created', models.DateTimeField(auto_now=True)),
                ('language_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('military_obligations_fulfilled', models.BooleanField()),
                ('professional_profile', models.CharField(max_length=500)),
                ('personal_info_created', models.DateTimeField(auto_now=True)),
                ('personal_info_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=252)),
                ('project_description', models.CharField(max_length=255)),
                ('project_published', models.BooleanField()),
                ('project_created', models.DateTimeField(auto_now=True)),
                ('project_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(max_length=252)),
                ('skill_description', models.CharField(max_length=252)),
                ('skill_type', models.CharField(max_length=2)),
                ('skill_created', models.DateTimeField(auto_now=True)),
                ('skill_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('skill_type_created', models.DateTimeField(auto_now=True)),
                ('skill_type_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_experience_title', models.CharField(max_length=252)),
                ('working_experience_description', models.CharField(max_length=252)),
                ('working_experience_published', models.BooleanField()),
                ('working_experience_start', models.DateField()),
                ('working_experience_end', models.DateField()),
                ('working_experience_created', models.DateTimeField(auto_now=True)),
                ('working_experience_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
