# Generated by Django 5.0.4 on 2024-05-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='education_banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='personal_banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
